# Generated by Django 3.0.3 on 2020-06-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200617_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('number', models.IntegerField(default=0, max_length=10)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
    ]
